worker_processes auto;

events {
    worker_connections 1024;
}

http {

    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;


    server {
        listen 443 ssl;
        server_name zizon-tomato.cloud;

	 resolver 127.0.0.11 valid=10s;

        ssl_certificate /etc/letsencrypt/live/zizon-tomato.cloud/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/zizon-tomato.cloud/privkey.pem;

        # 일반 API
        location /api/ {
            set $api_backend http://nest:3000;
            rewrite ^/api/(.*)$ /$1 break;
            proxy_pass $api_backend;

            proxy_http_version 1.1;

            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        # SSE
        location /api/sse/ {
            set $sse_backend http://nest:3000;
            rewrite ^/api/(.*)$ /$1 break;
            proxy_pass $sse_backend;

            proxy_http_version 1.1;
            proxy_set_header Connection '';

            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;

            proxy_cache off;
            proxy_buffering off;

            proxy_read_timeout 1h;
        }

	# React
	root /home/ubuntu/wannabe-ketchup/dist;
	index index.html;

	location / {
		try_files $uri $uri/ /index.html;
	}
    }

    server {
        listen 80;
        server_name zizon-tomato.cloud;

        return 301 https://$host$request_uri;
    }
}
