worker_processes auto;

events {
    worker_connections 1024;
}

http {

    # nest.js 컨테이너 이름으로 수정
    upstream nestjs_server {
        server nest:3000;
    }

    server {
        listen 443 ssl;
        server_name api.zizon-tomato.cloud;

        ssl_certificate /etc/letsencrypt/live/api.zizon-tomato.cloud/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/api.zizon-tomato.cloud/privkey.pem;

        # 일반 API
        location / {
            proxy_pass http://nestjs_server;

            proxy_http_version 1.1;

            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        # SSE
        location /sse/ {
            proxy_pass http://nestjs_server;

            proxy_http_version 1.1;
            proxy_set_header Connection '';

            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;

            proxy_cache off;
            proxy_buffering off;

            proxy_read_timeout 1h;
        }
    }

    server {
        listen 80;
        server_name api.zizon-tomato.cloud;

        return 301 https://$host$request_uri;
    }
}